"""Initial Migration

Revision ID: 0f7c5a28d573
Revises: 6aafc9d8dc58
Create Date: 2018-09-13 11:38:21.114155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7c5a28d573'
down_revision = '6aafc9d8dc58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category', sa.String(length=255), nullable=True))
    op.drop_column('categories', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('categories', 'category')
    # ### end Alembic commands ###
