"""Initial Migration

Revision ID: 540ba63a84e2
Revises: 51329701d465
Create Date: 2018-09-12 08:10:26.665472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540ba63a84e2'
down_revision = '51329701d465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'category')
    op.drop_column('pitches', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
