"""Initial Migration

Revision ID: ef422f7e32ba
Revises: fce3c8653b99
Create Date: 2018-09-13 11:16:10.748327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef422f7e32ba'
down_revision = 'fce3c8653b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category', sa.String(length=255), nullable=True))
    op.drop_column('categories', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('categories', 'category')
    # ### end Alembic commands ###
